{
 "title": "Example - Workload Golden Signals",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "cluster", "label": "cluster", "query": "prometheus" },
   {
    "name": "namespace",
    "query": {
     "query": "label_values(groundcover_resource_total_counter{type=\"container_info\"}, namespace)"
    }
   },
   {
    "name": "workload",
    "query": {
     "query": "label_values(groundcover_resource_total_counter{type=\"container_info\", namespace=~\"$namespace\"}, workload_name)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": " ",
   "type": "text",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 0 },
   "options": {
    "content": "<div align=\"center\" style=\"text-align: center\" style=\"background-color:aquamarine;\">\n    <img  src=\"https://help.sumologic.com/img/icons/metrics.png\"  width=\"38%\"  title=\"groundcover\" />\n</div>"
   }
  },
  {
   "title": "🔹  HTTP Requests",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(groundcover_workload_total_counter{type=~\".*http|grpc\", role=\"server\",namespace=\"$namespace\", workload_name=\"$workload\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "🔹 HTTP Error Rate",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(groundcover_workload_error_counter{type=~\".*http|grpc\", role=\"server\",namespace=\"$namespace\", workload_name=\"$workload\"}[$__rate_interval])/ rate(groundcover_workload_total_counter{type=~\".*http|grpc\", role=\"server\",namespace=\"$namespace\", workload_name=\"$workload\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "🔹 HTTP P50 Latency",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(groundcover_workload_latency_seconds{type=~\".*http|grpc\", role=\"server\",namespace=\"$namespace\", workload_name=\"$workload\", quantile=\"0.50\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "🔹 HTTP Latency ",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 9, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg(groundcover_workload_latency_seconds{type=~\".*http|grpc\", role=\"server\",namespace=\"$namespace\", workload_name=\"$workload\", quantile=\"0.50\"})",
     "legendFormat": "P50"
    },
    {
     "expr": "avg(groundcover_workload_latency_seconds{type=~\".*http|grpc\", role=\"server\",namespace=\"$namespace\", workload_name=\"$workload\", quantile=\"0.95\"})",
     "legendFormat": "P95"
    },
    {
     "expr": "avg(groundcover_workload_latency_seconds{type=~\".*http|grpc\", role=\"server\",namespace=\"$namespace\", workload_name=\"$workload\", quantile=\"0.99\"})",
     "legendFormat": "P99"
    }
   ]
  },
  { "title": "🌀  Pods", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": " 🎚  CPU Usage (by Pod)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "mCPU" } },
   "targets": [
    {
     "expr": "topk(50, avg by (pod_name) (rate(groundcover_container_m_cpu_usage_seconds_total{namespace=\"$namespace\", workload_name=\"$workload\"}[60s])))",
     "legendFormat": " {{pod_name}}"
    }
   ]
  },
  {
   "title": "🧠 Memory Usage (by Pod)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "topk(50, avg by (pod_name) (groundcover_container_mem_working_set_bytes{namespace=\"$namespace\", workload_name=\"$workload\"}))",
     "legendFormat": " {{pod_name}}"
    }
   ]
  },
  { "title": "⚡  Performance Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "🔺  Errors by Status Code (⬇)",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 19, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate (groundcover_resource_error_counter{type=~\".*http|grpc\", role=\"server\", namespace=\"$namespace\", workload_name=\"$workload\"}[$__rate_interval])) by (response_status_code)",
     "legendFormat": "{{response_status_code}}"
    }
   ]
  },
  {
   "title": "🔺 Errors by Status Code (⬇)",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 5, "x": 19, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(groundcover_resource_error_counter{type=~\".*http|grpc\", role=\"server\", namespace=\"$namespace\", workload_name=\"$workload\"}) by (response_status_code)",
     "legendFormat": "{{response_status_code}}"
    }
   ]
  },
  {
   "title": "🔺 Error Rate by API (⮃)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 16, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "topk(25, sum(rate(groundcover_resource_error_counter{type=~\".*http|grpc\", role=\"server\", namespace=\"$namespace\", workload_name=\"$workload\"}[$__rate_interval])) by (clustered_path))",
     "legendFormat": "⬇ {{clustered_path}}"
    },
    {
     "expr": "topk(25, sum(rate(groundcover_resource_error_counter{type=~\".*http|grpc\", role=\"client\", namespace=\"$namespace\", workload_name=\"$workload\"}[$__rate_interval])) by (clustered_path))",
     "legendFormat": "⬆ {{clustered_path}}"
    }
   ]
  },
  {
   "title": "🚨 Slowest APIs (⮃)",
   "type": "bargauge",
   "gridPos": { "h": 18, "w": 8, "x": 16, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(10, (avg(groundcover_resource_latency_seconds{type=~\"http|grpc\", role=\"server\", namespace=\"$namespace\", workload_name=\"$workload\", quantile=\"0.50\"}) by (clustered_path) != 0))",
     "legendFormat": "⬇ {{clustered_path}}"
    },
    {
     "expr": "topk(10, (avg(groundcover_resource_latency_seconds{type=~\"http|grpc\", role=\"client\", namespace=\"$namespace\", workload_name=\"$workload\", quantile=\"0.50\"}) by (clustered_path) != 0))",
     "legendFormat": "⬆ {{clustered_path}}"
    }
   ]
  },
  {
   "title": "🚨  P50 Latency by API (⮃)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 16, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "topk(25, avg(groundcover_resource_latency_seconds{type=~\".*http|grpc\", role=\"server\", namespace=\"$namespace\", workload_name=\"$workload\", quantile=\"0.50\"}) by (clustered_path))",
     "legendFormat": "⬇ {{clustered_path}}"
    },
    {
     "expr": "topk(25, avg(groundcover_resource_latency_seconds{type=~\".*http|grpc\", role=\"client\", namespace=\"$namespace\", workload_name=\"$workload\", quantile=\"0.50\"}) by (clustered_path))",
     "legendFormat": "⬆ {{clustered_path}}"
    }
   ]
  }
 ]
}